routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


// Resource Logger
Route::get('logger/api/{logId}', 'LoggerController@readlog')->name('logger.api');
Route::resource('logger', 'LoggerController');

app/Logger.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Logger extends Model
{
    protected $fillable = ['log_name','log_path','user_id'];
    /**
     * Get the user that owns the phone.
     */
    public function user(){
        return $this->belongsTo(App\User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    /**
     * Get the logs for the blog post.
     */
    public function logs(){
        return $this->hasMany(App\Logger::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Logger;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        if($request->session()->has('current_line')){
            $request->session()->forget('current_line');
        }
        $logger = Logger::get();
        return view('home', compact('logger'));
    }
}

app/Http/Controllers/LoggerController.php
<?php

namespace App\Http\Controllers;

use App\Logger;
use App\Helpers\Tail;
use Illuminate\Http\Request;
use Auth;

class LoggerController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->session()->has('current_line')){
            $request->session()->forget('current_line');
        }
        
        $logger = Logger::where('user_id', Auth::user()->id)->get();
        $num = 1;
        return view('logger.index',compact('logger','num'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('logger.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'log_name' => 'required',
            'log_path' => 'required|regex:/^.+\.log$/'
        ]);
    
        $logger = new Logger($request->all());
        $logger->user_id = Auth::user()->id;
        
        if($logger->save()){
            return redirect()->route('logger.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Logger  $logger
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,Logger $logger){
        return view('logger.show', compact('logger'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Logger  $logger
     * @return \Illuminate\Http\Response
     */
    public function edit(Logger $logger){
        return view('logger.edit', compact('logger'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Logger  $logger
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Logger $logger){

        $this->validate($request,[
            'log_name' => 'required',
            'log_path' => 'required|regex:/^.+\.log$/'
        ]);
        $update = $logger->update($request->all());

        if($update){
            return redirect()->route('logger.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Logger  $logger
     * @return \Illuminate\Http\Response
     */
    public function destroy(Logger $logger)
    {
        $logger->delete();
        return redirect()->route('logger.index');
    }
    /**
     * Read Log.
     *
     * @param  \App\Logger  $logger
     * @return \Illuminate\Http\Response
     */
    public function readlog(Request $request,$logId)
    {
        $log = Logger::find($logId);
        $file = $log->log_path;
        $total_lines = intval(shell_exec('cat ' . escapeshellarg($file) . ' | wc -l'));
        $current_line = intval($request->session()->get('current_line')[$logId]);

        $line_total = $total_lines - $current_line;

        $lines = "";
        if($request->session()->has('current_line') && $current_line < $total_lines){
            $lines = shell_exec('tail -n'.$line_total. ' ' . escapeshellarg($file));
        }elseif(!$request->session()->has('current_line')){
            $lines = shell_exec('tail -n10 ' . escapeshellarg($file));
        }

        $lines_array = array_filter(preg_split('#[\r\n]+#', trim($lines)));

        if(count($lines_array) && $current_line < $total_lines){
            $request->session()->put('current_line', array( $logId => $total_lines));
            $array_current = array_slice($lines_array, -$line_total, $line_total, true);
            return response()->json(["status" => "success", "value" => $array_current], 200);
        }
        return response()->json(["status" => "error", "value" => "Data Not Updated"], 200);
    }

}

resources/views/app/dashboard.blade.php
@extends('layouts.app')

@section('title', 'Admin Dashboard')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Dashboard</h1>
    </div>

    <div class="section-body">
    </div>
  </section>
@endsection

resources/views/app/table.blade.php
@extends('layouts.app')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Package Management</h1>
    </div>
    <div class="section-body">
      <h2 class="section-title">List of Packages Question</h2>
      <p class="section-lead">This page is for managing packages including questions and answers.</p>
      <div class="card">
        <div class="card-body p-0">
          <div class="table-responsive">
            <table class="table table-striped table-md">
              <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>Level</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>1</td>
                <td>Lorem</td>
                <td>Lorem ipsum dolor sit amet, consectetur adipisicing.</td>
                <td>3</td>
                <td></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('page_name')
    Dashboard
@endsection
@section('content')
<div class="container">
    <div class="row">
        @foreach ($logger as $item)
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">{{$item->log_name}} 
                    <a  class="ml-3 btn btn-primary" href="{{ route('logger.show',$item->id) }}"><i class="fas fa-eye"></i> View</a>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
@extends('layouts.skeleton')

@section('app')
  <div class="main-wrapper">
    <div class="navbar-bg"></div>
    <nav class="navbar navbar-expand-lg main-navbar">
      @include('partials.topnav')
    </nav>
    <div class="main-sidebar">
      @include('partials.sidebar')
    </div>

    <!-- Main Content -->
    <div class="main-content">
      <section class="section">
        <div class="section-header">@yield('page_name')</div>
          <div class="section-body">
             @yield('content')
          </div>
      </section>
    </div>
    <footer class="main-footer">
      @include('partials.footer')
    </footer>
  </div>
@endsection

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Login &mdash; {{ env('APP_NAME') }}</title>
  <link rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>

<body>
  <div id="app">
    <section class="section">
      @yield('content')
    </section>
  </div>
  <script src="{{ mix('js/manifest.js') }}"></script>
  <script src="{{ mix('js/vendor.js') }}"></script>
  <script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/skeleton.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>@yield('title', 'Home') &mdash; {{ env('APP_NAME') }}</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" href="{{ mix('css/app.css') }}">
  @stack('stylesheet')
</head>

<body>
<div id="app">
  @yield('app')
</div>
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
@stack('javascript')
</body>
</html>

resources/views/logger/create.blade.php
@extends('layouts.app')
@section('page_name')
    Add Logger
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('logger.store') }}">
                         @csrf
                       <div class="form-group">
                         <label for="email">Log Name</label>
                         <input id="logname" type="text" class="form-control @error('logname') is-invalid @enderror" placeholder="My Log name" name="log_name" value="{{ old('logname') }}" autofocus>
                         @error('logname')
                             <span class="invalid-feedback" role="alert">
                                 <strong>{{ $message }}</strong>
                             </span>
                         @enderror
                       </div>
         
                       <div class="form-group">
                         <div class="d-block">
                             <label for="password" class="control-label">Log Path</label>
                         </div>
                         <input id="logpath" type="text" class="form-control @error('logpath') is-invalid @enderror" placeholder="/path/to/very/important.log" name="log_path">
                         @error('logpath')
                             <span class="invalid-feedback" role="alert">
                                 <strong>{{ $message }}</strong>
                             </span>
                         @enderror
                       </div>

                       <div class="form-group">
                         <button type="submit" class="btn btn-primary btn-lg" tabindex="4"><i class="fas fa-plus"></i>  Add Log</button>
                         <a href="{{route('logger.index')}}" role="button" class="btn btn-lg" tabindex="4">Cancel</a>
                       </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/logger/edit.blade.php
@extends('layouts.app')
@section('page_name')
    Edit Logger
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('logger.update', $logger->id) }}">
                         @csrf
                         @method('PUT')
                       <div class="form-group">
                         <label for="email">Log Name</label>
                         <input id="logname" type="text" class="form-control @error('logname') is-invalid @enderror" placeholder="My Log name" name="log_name" value="{{$logger->log_name}}" autofocus>
                         @error('logname')
                             <span class="invalid-feedback" role="alert">
                                 <strong>{{ $message }}</strong>
                             </span>
                         @enderror
                       </div>
         
                       <div class="form-group">
                         <div class="d-block">
                             <label for="password" class="control-label">Log Path</label>
                         </div>
                         <input id="logpath" type="text" class="form-control @error('logpath') is-invalid @enderror" placeholder="/path/to/very/important.log" value="{{$logger->log_path}}" name="log_path">
                         @error('logpath')
                             <span class="invalid-feedback" role="alert">
                                 <strong>{{ $message }}</strong>
                             </span>
                         @enderror
                       </div>

                       <div class="form-group">
                         <button type="submit" class="btn btn-primary btn-lg" tabindex="4"><i class="fas fa-plus"></i>  Add Log</button>
                         <a href="{{route('logger.index')}}" role="button" class="btn btn-lg" tabindex="4">Cancel</a>
                       </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/logger/index.blade.php
@extends('layouts.app')
@section('page_name')
    Logger List <a href="{{route('logger.create')}}" class="ml-3 btn btn-primary"><i class="fas fa-plus"></i> Add Logger</a>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table id="datatable" class="table table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Logger Name</th>
                            <th scope="col">Logger Path</th>
                            <th scope="col" class="text-center" colspan="2">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            @forelse ($logger as $item)
                                <tr>
                                    <td>{{$num++}}</td>
                                    <td>{{$item->log_name}}</td>
                                    <td>{{$item->log_path}}</td>
                                    <td>
                                        <a  class="btn btn-primary" href="{{ route('logger.edit',$item->id) }}">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{route('logger.destroy', $item->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr class="text-center">
                                    <td colspan="12">No Data</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/logger/show.blade.php
@extends('layouts.app')
@section('page_name')
    Logger
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body overflow-auto" style="max-height:500px">
                    <ul id="msg"></ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('javascript')
<script>
    $(document).ready(function() {
        var url =  "{!! route('logger.api', $logger->id) !!}"
        setInterval(function(){
            $.getJSON(url, function( data ) {
                var $log = $('#msg');
                console.log(data);
                if (data.status == 'success') {
                    $.each( data.value, function( key, val ) {
                            $log.append( "<li>" + val + "</li>" );
                    });
                }
            });
        },2000);
    });
</script>
@endpush

resources/views/partials/footer.blade.php
<div class="footer-left">
  Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
</div>
<div class="footer-right">
  2.3.0
</div>

resources/views/partials/sidebar.blade.php
<aside id="sidebar-wrapper">
  <div class="sidebar-brand">
    <a href="">{{ env('APP_NAME') }}</a>
  </div>
  <div class="sidebar-brand sidebar-brand-sm">
    <a href="#">{{ strtoupper(substr(env('APP_NAME'), 0, 2)) }}</a>
  </div>
  <ul class="sidebar-menu">
    <li class="menu-header">Dashboard</li>
    <li class="{{set_active('home')}}"><a class="nav-link" href="{{ route('home') }}"><i class="fa fa-columns"></i> <span>Dashboard</span></a></li>
    <li class="menu-header">Server Config</li>
    <li class="{{set_active(['logger.index','logger.create','logger.show'])}}"><a class="nav-link" href="{{route('logger.index')}}"><i class="fa fa-plus"></i> <span>Add Log</span></a></li>
  </ul>
</aside>

resources/views/partials/topnav.blade.php
<form class="form-inline mr-auto" action="">
  <ul class="navbar-nav mr-3">
    <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
  </ul>
</form>
<ul class="navbar-nav navbar-right">
  <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
    <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::user()->name}}</div></a>
    <div class="dropdown-menu dropdown-menu-right">
      <div class="dropdown-title">Welcome, {{Auth::user()->name}}</div>
      <a href="#" class="dropdown-item has-icon">
        <i class="far fa-user"></i> Profile Settings
      </a>
      <div class="dropdown-divider"></div>
        <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item has-icon text-danger">
          <i class="fas fa-sign-out-alt"></i> Logout
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        </form>
    </div>
  </li>
</ul>